### ISSUE TITLE
update please

### ISSUE THREAD

**Issue by LeePC** [Tarferi/EUD-Enabler#1]
starcraft update........
update please

**Comment by Tarferi** [comment]
The what now? 1.16.1 came out 11 years ago.

**Comment by LeePC** [comment]
Remasted Version EUD update please

**Comment by Tarferi** [comment]
Yeah, I'm not gonna spend another 5 hours figuring out what is changed in SCR. Give me some specs or a link.

**Comment by LeePC** [comment]
my spec?????
